### ISSUE TITLE
Writing JUnit tests.

### ISSUE THREAD

**Issue by GnikDroy** [GnikDroy/DownloadManager#3]
Need to write JUnit tests for the downloadmanager package.

**Comment by jgolatkar** [comment]
Hi.. If nobody is currently working on this, I would like to give it a try

**Comment by GnikDroy** [comment]
Thanks. I will leave it to you then, The project is still in infancy, so feel free to modify any code, add a issue and request a pull request.

**Comment by GnikDroy** [comment]
@jgolatkar Thanks. I will leave it to you then. The project is still in infancy, so feel free to modify any code, add a issue and request a pull request.

**Comment by mehulumistry** [comment]
Hi! I am also interested in working on this project. Is it okay if we collaborate @jgolatkar ?

**Comment by jgolatkar** [comment]
@mehulumistry Hi. Yes, we can collaborate!

**Comment by GnikDroy** [comment]
@jgolatkar @mehulumistry Hey guys, the repo size is greater than 30MB(unusual for a small project like this). So, I re-wrote history, removed all binary files and reduced repo size to less than 1 MB. Make sure you get a fresh clone of the repository(refork) and transfer your changes to the new repo. Sorry for the hassle, but this had to be done.

**Comment by LoicB** [comment]
Hello guys!
Maybe I could give a hand?
I started to write a couple of unit tests. Please let me know if you have done anything.
Thanks

**Comment by GnikDroy** [comment]
Closing this for now. Will do after significant refactoring
