### ISSUE TITLE
Support building through maven and gradle

### ISSUE THREAD

**Issue by royshahaf** [GnikDroy/DownloadManager#4]
Hello,

While I have no inherent problem with ANT, I think that by allowing people to build the project using maven and gradle you can get more people to help out (as not everyone is inclined to download ANT and most people have maven and/or gradle readily available)

**Comment by GnikDroy** [comment]
You are right. Maven and gradle give a bit more structure to the project. It allows me to handle dependencies more easily too.

**Comment by GnikDroy** [comment]
Fixed with 929fc690bc15f9d47f89b37c77cec43b6580c01a
